import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html className="h-full" lang="en">
        <body className={clsx("relative antialiased h-full", roboto.className)}>
           <main className="relative flex flex-col min-h-screen">
              <div className="felx-grow flex-1">{children}</div>
           </main>
        </body>
     </html>
  );
}
